/**
 * @file SerialCommand.h
 * @brief Serial command parser for USB configuration interface
 *
 * Provides a simple AT-style command interface for:
 * - Reading/writing calibration parameters (CFG)
 * - CAN configuration file management (CAN)
 * - OTA firmware updates (OTA)
 * - Enabling/disabling CAN debug logs (LOG)
 * - System information and control (SYS)
 */

#ifndef SERIAL_COMMAND_H
#define SERIAL_COMMAND_H

#include <Arduino.h>
#include "version.h"

// =============================================================================
// VERSION INFO
// =============================================================================

// APP_VERSION and BUILD_DATE are generated by tools/git_version.py at build time
#define FIRMWARE_VERSION APP_VERSION
#define FIRMWARE_DATE    BUILD_DATE

// =============================================================================
// CONFIGURATION
// =============================================================================

#define CMD_BUFFER_SIZE     320  // Max command length (16 prefix + 240 base64 + 1 null + margin)
#define CMD_PROMPT          "> " // Command prompt (optional)
#define CAN_UPLOAD_MAX_SIZE 8192 // Max JSON config file size (8KB)

// =============================================================================
// PUBLIC API
// =============================================================================

/**
 * @brief Initialize serial command parser
 */
void serialCommandInit();

/**
 * @brief Process incoming serial data
 */
void serialCommandProcess();

/**
 * @brief Check if CAN logging is enabled
 * @return true if LOG ON was called
 */
bool isCanLogEnabled();

/**
 * @brief Check if OTA update is in progress
 */
bool isOtaInProgress();

/**
 * @brief Auto-abort OTA if no DATA received within OTA_DATA_TIMEOUT_MS.
 * Call from loop() when OTA is active.
 */
void serialCommandCheckOtaTimeout();

#ifdef UNIT_TEST
/** Test-only entry point — calls the internal processCommand() directly */
void testProcessCommand(const char* line);
#endif

#endif // SERIAL_COMMAND_H
