import subprocess
import os
from datetime import datetime

Import("env")

# Paths
include_dir = os.path.join(env.subst("$PROJECT_DIR"), "include")
version_h_path = os.path.join(include_dir, "version.h")

# Check if version.h exists and if it was generated by CI
skip_gen = False
if os.path.exists(version_h_path):
    with open(version_h_path, 'r') as f:
        if "// Generated by GitHub Action" in f.read():
            print("\n--- [VERSION GENERATOR] Using existing CI-generated version.h ---\n")
            skip_gen = True

if not skip_gen:
    def get_app_version():
        # 1. Environment variable (e.g. APP_VERSION=v1.2.3 pio run)
        version = os.environ.get("APP_VERSION")
        if version:
            return version
        
        # 2. Local git hash
        try:
            return subprocess.check_output(["git", "rev-parse", "--short", "HEAD"]).strip().decode("utf-8")
        except Exception:
            return "dev"

    version = get_app_version()
    date = datetime.now().strftime("%b %d %Y")

    print(f"\n--- [VERSION GENERATOR] Creating local version.h. Version: {version}, Date: {date} ---\n")

    if not os.path.exists(include_dir):
        os.makedirs(include_dir)

    with open(version_h_path, "w") as f:
        f.write("// Generated file - do not edit\n")
        f.write(f'#define APP_VERSION "{version}"\n')
        f.write(f'#define BUILD_DATE "{date}"\n')
